import type { SdkworkOrderPcRouteContribution } from "@sdkwork/order-pc-core";

export const sdkworkOrderPcAdminTradeRoutes = [
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.workbench",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/overview",
    permissionHint: "commerce.orders.read",
    screen: "trade-workbench",
    surface: "backend-admin",
    title: "交易中心工作台",
    titleKey: "admin.trade.workbench.title",
  },
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.orders",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/orders",
    permissionHint: "commerce.orders.read",
    screen: "trade-orders",
    surface: "backend-admin",
    title: "订单监管",
    titleKey: "admin.orders.title",
  },
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.after-sales",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/after-sales",
    permissionHint: "commerce.orders.read",
    screen: "trade-after-sales",
    surface: "backend-admin",
    title: "售后单",
    titleKey: "admin.trade.afterSales.title",
  },
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.shipments",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/shipments",
    permissionHint: "commerce.orders.read",
    screen: "trade-shipments",
    surface: "backend-admin",
    title: "发货管理",
    titleKey: "admin.trade.shipments.title",
  },
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.refunds",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/refunds",
    permissionHint: "commerce.orders.read",
    screen: "trade-refunds",
    surface: "backend-admin",
    title: "退款单",
    titleKey: "admin.trade.refunds.title",
  },
  {
    auth: "required",
    capability: "admin-trade",
    domain: "commerce",
    id: "admin.commerce.trade.withdrawals",
    packageName: "@sdkwork/order-pc-admin-trade",
    path: "/admin/trade/withdrawals",
    permissionHint: "commerce.orders.read",
    screen: "trade-withdrawals",
    surface: "backend-admin",
    title: "提现单",
    titleKey: "admin.trade.withdrawals.title",
  },
] as const satisfies readonly SdkworkOrderPcRouteContribution[];
