//! Authored API assembly bootstrap for sdkwork-order.
//! Route inventory is regenerated by `pnpm api:assembly:materialize`.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use std::sync::Arc;

use axum::Router;
use sdkwork_database_spi::{DefaultDatabaseModule, SpiError};
use sdkwork_database_sqlx::DatabasePool;
use sdkwork_order_service_host::OrderServiceHost;
pub use sdkwork_web_bootstrap::ApiAssemblyContribution;
use sdkwork_web_bootstrap::{ContractFallbackConfig, ReadinessCheck, ReadinessFuture, WebModule};
use sdkwork_web_core::HttpRouteManifest;

pub type ApiAssembly = ApiAssemblyContribution;

pub struct BusinessRouterAssembly {
    pub router: Router,
}

pub struct OrderAssemblyContract;

#[derive(Clone)]
struct OrderReadiness {
    pool: DatabasePool,
}

impl ReadinessCheck for OrderReadiness {
    fn check(&self) -> ReadinessFuture<'_> {
        let pool = self.pool.clone();
        Box::pin(async move {
            match pool.test_connection().await {
                Ok(true) => Ok(()),
                Ok(false) => Err("order database readiness query returned no row".to_owned()),
                Err(error) => Err(format!("order database readiness check failed: {error}")),
            }
        })
    }
}

impl OrderAssemblyContract {
    pub async fn from_database_pool(pool: DatabasePool) -> Result<Self, String> {
        OrderServiceHost::from_database_pool(pool).await?;
        Ok(Self)
    }

    pub fn database_module() -> Result<DefaultDatabaseModule, SpiError> {
        sdkwork_order_database_host::database_module()
    }

    pub fn app_route_manifest() -> HttpRouteManifest {
        sdkwork_routes_order_app_api::http_route_manifest::app_route_manifest()
    }

    pub fn contract_fallback_config() -> ContractFallbackConfig {
        let mut config = ContractFallbackConfig::from_manifest(&Self::app_route_manifest());
        let backend = ContractFallbackConfig::from_manifest(
            &sdkwork_routes_order_backend_api::http_route_manifest::backend_route_manifest(),
        );
        config.manifest_paths.extend(backend.manifest_paths);
        config
    }
}

pub async fn assemble_api_router(host: Arc<OrderServiceHost>) -> Result<ApiAssembly, String> {
    start_runtime_workers(&host);
    let router = Router::new()
        .merge(sdkwork_routes_order_app_api::gateway_mount(host.clone()).await)
        .merge(sdkwork_routes_order_backend_api::gateway_mount(host.clone()).await);
    let mut routes = Vec::new();
    routes.extend_from_slice(sdkwork_routes_order_app_api::gateway_route_manifest().routes());
    routes.extend_from_slice(sdkwork_routes_order_backend_api::gateway_route_manifest().routes());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-order",
        "SDKWork Order API",
        router,
        HttpRouteManifest::from_owned_routes(routes),
        Vec::new(),
        Arc::new(OrderReadiness {
            pool: host.database_pool().clone(),
        }),
    )
}

pub async fn assemble_api_router_with_pool(pool: DatabasePool) -> Result<ApiAssembly, String> {
    let host = Arc::new(OrderServiceHost::from_database_pool(pool).await?);
    assemble_api_router(host).await
}

pub async fn assemble_backend_business_router(
    host: Arc<OrderServiceHost>,
) -> BusinessRouterAssembly {
    BusinessRouterAssembly {
        router: sdkwork_routes_order_backend_api::gateway_mount(host).await,
    }
}

/// Builds the raw Order App API for a gateway-owned Web Framework layer.
pub async fn assemble_app_api_contribution() -> Result<ApiAssemblyContribution, String> {
    let host = Arc::new(OrderServiceHost::from_env().await?);
    start_runtime_workers(&host);
    assemble_app_api_contribution_with_host(host)
}

pub async fn assemble_app_api_contribution_with_pool(
    pool: DatabasePool,
) -> Result<ApiAssemblyContribution, String> {
    let host = Arc::new(OrderServiceHost::from_database_pool(pool).await?);
    start_runtime_workers(&host);
    assemble_app_api_contribution_with_host(host)
}

fn start_runtime_workers(host: &Arc<OrderServiceHost>) {
    sdkwork_order_service_host::spawn_order_expiration_scheduler(host.clone());
    sdkwork_order_service_host::spawn_payment_compensation_worker(host.clone());
}

fn assemble_app_api_contribution_with_host(
    host: Arc<OrderServiceHost>,
) -> Result<ApiAssemblyContribution, String> {
    let route_manifest = OrderAssemblyContract::app_route_manifest();
    let router = sdkwork_routes_order_app_api::build_order_app_business_router(host.clone());
    ApiAssemblyContribution::from_manifest(
        "sdkwork-order",
        "SDKWork Order App API",
        router,
        route_manifest,
        Vec::new(),
        Arc::new(OrderReadiness {
            pool: host.database_pool().clone(),
        }),
    )
}

/// Same as [`web_module`] but composed on a process-shared database pool
/// (platform gateways, API_ASSEMBLY_SPEC §4.1.1).
pub async fn web_module_with_pool(pool: DatabasePool) -> Result<WebModule, String> {
    Ok(WebModule::from_contribution(assemble_api_router_with_pool(pool).await?))
}
