-- SDKWork order consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_order_baseline.sql
-- SDKWork order consolidated initialization baseline (postgres)
-- Generated by reset-database-initialization-state.mjs
-- Application is in initialization state: full DDL lives here; migrations/ is reserved for post-GA changes.

-- baseline source: ddl/baseline/postgres/0001_order_baseline.sql
-- sdkwork:baseline
-- module: order
-- order-owned core and account-value tables

CREATE TABLE IF NOT EXISTS commerce_order (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    owner_user_id TEXT NOT NULL,
    order_no TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending_payment',
    subject TEXT NOT NULL,
    currency_code TEXT NOT NULL DEFAULT 'CNY',
    merchant_organization_id TEXT,
    shop_id TEXT,
    shipping_address_snapshot_json TEXT,
    shop_snapshot_json TEXT,
    payment_status TEXT,
    fulfillment_status TEXT,
    refund_status TEXT,
    request_no TEXT,
    idempotency_key TEXT,
    request_fingerprint TEXT,
    purchase_intent_key TEXT,
    membership_action TEXT,
    partner_id TEXT,
    partner_snapshot_json TEXT,
    created_at TEXT NOT NULL,
    paid_at TEXT,
    cancelled_at TEXT,
    expired_at TEXT,
    updated_at TEXT NOT NULL
);

ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS payment_status TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS fulfillment_status TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS refund_status TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS request_fingerprint TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS purchase_intent_key TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS membership_action TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS partner_id TEXT;
ALTER TABLE commerce_order ADD COLUMN IF NOT EXISTS partner_snapshot_json TEXT;

CREATE INDEX IF NOT EXISTS idx_order_partner_list
    ON commerce_order(tenant_id, organization_id, partner_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_owner_idempotency
    ON commerce_order(tenant_id, COALESCE(organization_id, '0'), owner_user_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_order_owner_list
    ON commerce_order(tenant_id, organization_id, owner_user_id, created_at DESC, id DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_order_active_purchase_intent
    ON commerce_order(
        tenant_id,
        COALESCE(organization_id, '0'),
        owner_user_id,
        subject,
        purchase_intent_key
    )
    WHERE purchase_intent_key IS NOT NULL
      AND status IN ('draft', 'pending', 'pending_payment', 'unpaid', 'wait_pay', 'created');

CREATE TABLE IF NOT EXISTS commerce_order_item (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    order_id TEXT NOT NULL,
    product_id TEXT,
    shop_id TEXT,
    sku_id TEXT,
    sku_snapshot_json TEXT,
    title TEXT,
    quantity BIGINT NOT NULL DEFAULT 1,
    unit_price_amount TEXT,
    discount_amount TEXT,
    tax_amount TEXT,
    total_amount TEXT,
    fulfillment_status TEXT,
    refund_status TEXT,
    created_at TEXT NOT NULL
);

ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS sku_snapshot_json TEXT;
ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS discount_amount TEXT;
ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS tax_amount TEXT;
ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS fulfillment_status TEXT;
ALTER TABLE commerce_order_item ADD COLUMN IF NOT EXISTS refund_status TEXT;

CREATE INDEX IF NOT EXISTS idx_order_item_order
    ON commerce_order_item(tenant_id, order_id, created_at, id);

CREATE TABLE IF NOT EXISTS commerce_checkout_session (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    checkout_session_no TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    source_type TEXT NOT NULL,
    status TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    promotion_snapshot_json TEXT NOT NULL DEFAULT '[]',
    request_hash TEXT NOT NULL,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    shop_id TEXT,
    merchant_organization_id TEXT,
    shop_snapshot_json TEXT,
    shipping_address_snapshot_json TEXT,
    expires_at TEXT,
    submitted_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_checkout_session_idempotency
    ON commerce_checkout_session(tenant_id, owner_user_id, idempotency_key);

CREATE TABLE IF NOT EXISTS commerce_checkout_line (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    checkout_session_id TEXT NOT NULL,
    product_id TEXT,
    shop_id TEXT,
    sku_id TEXT NOT NULL,
    sku_snapshot_json TEXT NOT NULL,
    selected_options_hash TEXT,
    quantity BIGINT NOT NULL,
    purchase_type TEXT NOT NULL,
    fulfillment_type TEXT NOT NULL,
    price_amount_snapshot TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    selected SMALLINT NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_checkout_line_session
    ON commerce_checkout_line(tenant_id, checkout_session_id, created_at, id);

CREATE TABLE IF NOT EXISTS commerce_checkout_quote (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    checkout_session_id TEXT NOT NULL,
    quote_no TEXT NOT NULL,
    original_amount TEXT NOT NULL,
    discount_amount TEXT NOT NULL,
    payable_amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    quote_status TEXT NOT NULL,
    expires_at TEXT,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_checkout_quote_session
    ON commerce_checkout_quote(tenant_id, checkout_session_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS commerce_fulfillment_order (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    fulfillment_no TEXT NOT NULL,
    order_id TEXT NOT NULL,
    fulfillment_type TEXT NOT NULL,
    status TEXT NOT NULL,
    warehouse_id TEXT,
    address_snapshot_id TEXT,
    provider_code TEXT,
    created_at TEXT NOT NULL,
    completed_at TEXT,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_fulfillment_order_type
    ON commerce_fulfillment_order(tenant_id, order_id, fulfillment_type);

CREATE TABLE IF NOT EXISTS commerce_order_amount_breakdown (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    order_id TEXT NOT NULL,
    order_item_id TEXT,
    allocation_type TEXT NOT NULL DEFAULT 'order_total',
    original_amount TEXT NOT NULL DEFAULT '0',
    discount_amount TEXT NOT NULL DEFAULT '0',
    payable_amount TEXT NOT NULL DEFAULT '0',
    currency_code TEXT,
    created_at TIMESTAMPTZ NOT NULL
);

ALTER TABLE commerce_order_amount_breakdown ADD COLUMN IF NOT EXISTS order_item_id TEXT;
ALTER TABLE commerce_order_amount_breakdown ADD COLUMN IF NOT EXISTS original_amount TEXT NOT NULL DEFAULT '0';

CREATE INDEX IF NOT EXISTS idx_order_amount_breakdown_order
    ON commerce_order_amount_breakdown(tenant_id, order_id, allocation_type, id);

CREATE TABLE IF NOT EXISTS commerce_recharge_package (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    external_id BIGINT NOT NULL,
    package_no TEXT NOT NULL,
    sku_id TEXT NOT NULL,
    name TEXT NOT NULL,
    price_amount TEXT NOT NULL,
    currency_code TEXT NOT NULL DEFAULT 'CNY',
    bonus_points BIGINT NOT NULL DEFAULT 0,
    discount BIGINT NOT NULL DEFAULT 100,
    status TEXT NOT NULL DEFAULT 'active',
    valid_from TEXT,
    valid_to TEXT,
    sort_weight BIGINT NOT NULL DEFAULT 0,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CONSTRAINT ck_recharge_package_discount_range CHECK (discount >= 1 AND discount <= 100)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_recharge_package_no
    ON commerce_recharge_package(tenant_id, COALESCE(organization_id, '0'), package_no);

CREATE UNIQUE INDEX IF NOT EXISTS uk_recharge_package_idempotency
    ON commerce_recharge_package(tenant_id, COALESCE(organization_id, '0'), idempotency_key);

CREATE INDEX IF NOT EXISTS idx_recharge_package_list
    ON commerce_recharge_package(tenant_id, organization_id, status, sort_weight, id);

CREATE INDEX IF NOT EXISTS idx_recharge_package_sku
    ON commerce_recharge_package(tenant_id, sku_id);

-- Cash-to-points exchange rule projection shared by the order read store and
-- the Cloud Router admin store. `rate` is the base points per base currency
-- unit; `remark` carries the recharge settings payload
-- (`baseCurrencyCode` + `currencyToCnyRates`). Timestamps are TIMESTAMPTZ
-- because the shared admin writer binds `::timestamptz` values.
CREATE TABLE IF NOT EXISTS commerce_exchange_rule (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    rule_no TEXT NOT NULL,
    source_asset_type TEXT NOT NULL,
    target_asset_type TEXT NOT NULL,
    rate TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    base_currency_code TEXT,
    remark TEXT,
    request_no TEXT,
    idempotency_key TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_commerce_exchange_rule_rate_decimal
        CHECK (rate ~ '^[0-9]+(\.[0-9]{1,6})?$' AND rate::numeric > 0),
    CONSTRAINT ck_commerce_exchange_rule_base_currency_code
        CHECK (base_currency_code IS NULL OR base_currency_code ~ '^[A-Z]{3}$')
);

CREATE TABLE IF NOT EXISTS commerce_exchange_currency_rate (
    id TEXT NOT NULL PRIMARY KEY,
    rule_id TEXT NOT NULL REFERENCES commerce_exchange_rule(id) ON DELETE CASCADE,
    currency_code TEXT NOT NULL,
    rate TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_commerce_exchange_currency_rate_code
        CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_commerce_exchange_currency_rate_decimal
        CHECK (rate ~ '^[0-9]+(\.[0-9]{1,6})?$' AND rate::numeric > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_exchange_currency_rate_pair
    ON commerce_exchange_currency_rate(rule_id, currency_code);

CREATE INDEX IF NOT EXISTS idx_exchange_currency_rate_rule
    ON commerce_exchange_currency_rate(rule_id);

CREATE UNIQUE INDEX IF NOT EXISTS uk_exchange_rule_pair
    ON commerce_exchange_rule(tenant_id, organization_id, source_asset_type, target_asset_type);

CREATE INDEX IF NOT EXISTS idx_exchange_rule_list
    ON commerce_exchange_rule(tenant_id, organization_id, status, updated_at, id);

CREATE TABLE IF NOT EXISTS commerce_account_value_package (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    package_code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    target_asset TEXT NOT NULL,
    grant_amount TEXT NOT NULL,
    bonus_amount TEXT NOT NULL DEFAULT '0',
    price_amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    sort_weight BIGINT NOT NULL DEFAULT 0,
    valid_from TEXT,
    valid_to TEXT,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    retired_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_account_value_package_code
    ON commerce_account_value_package(tenant_id, COALESCE(organization_id, '0'), package_code);

CREATE UNIQUE INDEX IF NOT EXISTS uk_account_value_package_idempotency
    ON commerce_account_value_package(tenant_id, COALESCE(organization_id, '0'), idempotency_key);

CREATE INDEX IF NOT EXISTS idx_account_value_package_list
    ON commerce_account_value_package(tenant_id, organization_id, target_asset, status, sort_weight, id);

CREATE TABLE IF NOT EXISTS commerce_token_bank_plan (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    plan_code TEXT NOT NULL,
    display_name TEXT NOT NULL,
    plan_period TEXT NOT NULL,
    grant_amount TEXT NOT NULL,
    bonus_amount TEXT NOT NULL DEFAULT '0',
    price_amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    renewal_policy TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    sort_weight BIGINT NOT NULL DEFAULT 0,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    retired_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_token_bank_plan_code
    ON commerce_token_bank_plan(tenant_id, COALESCE(organization_id, '0'), plan_code);

CREATE UNIQUE INDEX IF NOT EXISTS uk_token_bank_plan_idempotency
    ON commerce_token_bank_plan(tenant_id, COALESCE(organization_id, '0'), idempotency_key);

CREATE INDEX IF NOT EXISTS idx_token_bank_plan_list
    ON commerce_token_bank_plan(tenant_id, organization_id, status, sort_weight, plan_code);

CREATE TABLE IF NOT EXISTS commerce_order_refund_request (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    request_no TEXT NOT NULL,
    original_order_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    target_asset TEXT NOT NULL,
    amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    provider_amount TEXT,
    provider_currency_code TEXT,
    status TEXT NOT NULL DEFAULT 'requested',
    reason_code TEXT,
    reason_detail TEXT,
    review_comment TEXT,
    provider_reference_id TEXT,
    account_effect_reference_id TEXT,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_refund_request_idempotency
    ON commerce_order_refund_request(tenant_id, COALESCE(organization_id, '0'), owner_user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_order_refund_request_owner
    ON commerce_order_refund_request(tenant_id, organization_id, owner_user_id, status, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS commerce_order_withdrawal_request (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    request_no TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    target_asset TEXT NOT NULL,
    amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    provider_amount TEXT,
    provider_currency_code TEXT,
    status TEXT NOT NULL DEFAULT 'requested',
    payout_method TEXT,
    payout_account_ref TEXT,
    reason_code TEXT,
    review_comment TEXT,
    provider_reference_id TEXT,
    account_effect_reference_id TEXT,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_order_withdrawal_request_idempotency
    ON commerce_order_withdrawal_request(tenant_id, COALESCE(organization_id, '0'), owner_user_id, idempotency_key);

CREATE INDEX IF NOT EXISTS idx_order_withdrawal_request_owner
    ON commerce_order_withdrawal_request(tenant_id, organization_id, owner_user_id, status, created_at DESC, id DESC);

-- folded migration: migrations/postgres/0002_membership_order_purchase_intent.up.sql
-- sdkwork:migration
-- version: 0002
-- engine: postgres
-- module: order
-- description: Persist membership request fingerprints and reusable purchase intents.
-- reversible: false
-- transactional: true
-- lock: table
-- contract_version: 1.0.0

BEGIN;

ALTER TABLE commerce_order
    ADD COLUMN IF NOT EXISTS request_fingerprint TEXT,
    ADD COLUMN IF NOT EXISTS purchase_intent_key TEXT,
    ADD COLUMN IF NOT EXISTS membership_action TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS uk_membership_order_active_purchase_intent
    ON commerce_order (
        tenant_id,
        COALESCE(organization_id, '0'),
        owner_user_id,
        subject,
        purchase_intent_key
    )
    WHERE purchase_intent_key IS NOT NULL
      AND status IN ('draft', 'pending', 'pending_payment', 'unpaid', 'wait_pay', 'created');

COMMIT;

-- folded migration: migrations/postgres/0003_physical_goods_purchase.up.sql
ALTER TABLE commerce_order
    ADD COLUMN IF NOT EXISTS merchant_organization_id TEXT,
    ADD COLUMN IF NOT EXISTS shop_id TEXT,
    ADD COLUMN IF NOT EXISTS shipping_address_snapshot_json TEXT,
    ADD COLUMN IF NOT EXISTS shop_snapshot_json TEXT;

ALTER TABLE commerce_order_item
    ADD COLUMN IF NOT EXISTS product_id TEXT,
    ADD COLUMN IF NOT EXISTS shop_id TEXT;



CREATE UNIQUE INDEX IF NOT EXISTS uk_checkout_session_idempotency
    ON commerce_checkout_session(tenant_id, owner_user_id, idempotency_key);



CREATE INDEX IF NOT EXISTS idx_checkout_line_session
    ON commerce_checkout_line(tenant_id, checkout_session_id, created_at, id);



CREATE INDEX IF NOT EXISTS idx_checkout_quote_session
    ON commerce_checkout_quote(tenant_id, checkout_session_id, created_at DESC, id DESC);



CREATE UNIQUE INDEX IF NOT EXISTS uk_fulfillment_order_type
    ON commerce_fulfillment_order(tenant_id, order_id, fulfillment_type);

-- After-sales lifecycle tables (refund / return / exchange). Column shape
-- mirrors the e2e test migration so test and production schemas stay aligned.
CREATE TABLE IF NOT EXISTS commerce_after_sales_request (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    after_sales_no TEXT NOT NULL,
    order_id TEXT NOT NULL,
    owner_user_id TEXT NOT NULL,
    after_sales_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'submitted',
    refund_status TEXT NOT NULL DEFAULT 'none',
    return_status TEXT NOT NULL DEFAULT 'none',
    exchange_status TEXT NOT NULL DEFAULT 'none',
    reason_code TEXT NOT NULL,
    description TEXT,
    requested_amount TEXT NOT NULL,
    approved_amount TEXT NOT NULL DEFAULT '0.00',
    currency_code TEXT NOT NULL,
    requested_by_type TEXT NOT NULL DEFAULT 'buyer',
    requested_by TEXT,
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_after_sales_request_tenant_owner
    ON commerce_after_sales_request(tenant_id, owner_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_after_sales_request_idempotency
    ON commerce_after_sales_request(tenant_id, order_id, idempotency_key);

CREATE TABLE IF NOT EXISTS commerce_after_sales_request_item (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    after_sales_id TEXT NOT NULL,
    order_item_id TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    requested_amount TEXT NOT NULL,
    currency_code TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (after_sales_id) REFERENCES commerce_after_sales_request(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_after_sales_request_item_request
    ON commerce_after_sales_request_item(after_sales_id);

CREATE TABLE IF NOT EXISTS commerce_after_sales_event (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    after_sales_id TEXT NOT NULL,
    event_no TEXT NOT NULL,
    event_type TEXT NOT NULL,
    from_status TEXT,
    to_status TEXT NOT NULL,
    actor_type TEXT NOT NULL DEFAULT 'buyer',
    actor_id TEXT,
    request_id TEXT,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    FOREIGN KEY (after_sales_id) REFERENCES commerce_after_sales_request(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_after_sales_event_request
    ON commerce_after_sales_event(tenant_id, after_sales_id, created_at ASC);

CREATE TABLE IF NOT EXISTS commerce_after_sales_return_shipment (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    after_sales_id TEXT NOT NULL,
    return_shipment_no TEXT NOT NULL,
    carrier_code TEXT,
    tracking_no TEXT,
    status TEXT NOT NULL DEFAULT 'submitted',
    request_no TEXT NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (after_sales_id) REFERENCES commerce_after_sales_request(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_after_sales_return_shipment_idempotency
    ON commerce_after_sales_return_shipment(tenant_id, after_sales_id, idempotency_key);

-- Shipment lifecycle tables (merchant shipping / tracking). Column shape
-- mirrors the e2e test migration so test and production schemas stay aligned.
CREATE TABLE IF NOT EXISTS commerce_shipment (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    shipment_no TEXT NOT NULL,
    fulfillment_id TEXT NOT NULL,
    carrier_code TEXT NOT NULL,
    tracking_no TEXT,
    status TEXT NOT NULL,
    shipped_at TEXT,
    delivered_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_shipment_tenant_created
    ON commerce_shipment(tenant_id, created_at DESC);

CREATE TABLE IF NOT EXISTS commerce_shipment_package (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    shipment_id TEXT NOT NULL,
    package_no TEXT NOT NULL,
    package_type TEXT NOT NULL,
    tracking_no TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_commerce_shipment_package_shipment
    ON commerce_shipment_package(tenant_id, shipment_id, created_at ASC);

CREATE TABLE IF NOT EXISTS commerce_shipment_tracking_event (
    id TEXT NOT NULL PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    organization_id TEXT NOT NULL DEFAULT '0',
    shipment_id TEXT NOT NULL,
    tracking_event_no TEXT NOT NULL,
    event_type TEXT NOT NULL,
    event_status TEXT,
    event_time TEXT NOT NULL,
    location_text TEXT,
    created_at TEXT NOT NULL
);
